globalThis.facebookURL = "#";
globalThis.PinterestURL = "#";
globalThis.twitterURL = "#";
globalThis.redditURL = "#";
globalThis.siteUrl = "https:\/\/www.myrecipes.com";
globalThis.homepageTitle = "My Recipes";
globalThis.homepageTagline = "My Recipes - Discover delicious recipes for every occasion";
globalThis.email = 'contact@myrecipes.com';
globalThis.copyright = "2025 - 2026 My Recipes. All rights reserved.";
